# Usar una imagen base con Python 3.7
FROM python:3.7

# Establecer el directorio de trabajo en el contenedor
WORKDIR /app

# Copiar los archivos de requisitos primero para aprovechar la caché de Docker
COPY requirements.txt /app/

# Instalar las dependencias
RUN pip install -r requirements.txt

# Copiar el resto del código fuente al contenedor
COPY . /app/
